from pydantic import BaseModel, Field

from .ai_knowledges_model import AIKnowledge, KnowledgeType, Language


class AIKnowledgeBase(BaseModel):
    content: str
    type: KnowledgeType
    tags: list[str] = Field(default_factory=list)
    language: Language
    disabled: bool = Field(default=False)


class AIKnowledgeCreate(AIKnowledgeBase):
    pass


class AIKnowledgeUpdate(BaseModel):
    content: str | None = None
    type: KnowledgeType | None = None
    tags: list[str] | None = None
    language: Language | None = None
    disabled: bool | None = None


class VectorSearchResponse(BaseModel):
    document: AIKnowledge
    score: float = Field(
        description="Score de similitud semántica (0.0 a 1.0, mayor es mejor)"
    )


class AskRequest(BaseModel):
    question: str = Field(..., description="User question in natural language")
    language: Language | None = Field(None, description="Language filter (ES | EN)")


class AskResponse(BaseModel):
    answer: str = Field(..., description="Answer generated by LLM")
